function puzzle01 ()
 {

//	puzzledata = "title=Mots cachés&row1=WRTJVIIMPBYFMJS&row2=CTOIAKQKGTGKRAM&row3=HYZDELUCREHUZME&row4=ABUPENIOTNATKTI&row5=RNDDNARBEDLIHCV&row6=LWIMDBIYPLHSXTA&row7=EJHUZFNOCNASEBT&row8=SRDYOJUTBXLGOUC&row9=MDWLCISTOTDUGUO&row10=AOCILQHNOYRKUEQ&row11=RNBLNGXTGGIMKTW&row12=TIYZLYWSOECCEPJ&row13=EDURTREGWYMATDV&row14=LPKOUPNBAAOHMVL&row15=JSCICERONWSMFTS&numwords=1&word1=ALDRIC&";

	puzzledata = "title=Mots cachés&row1=WRTJVIIMPBYFMJS&row2=CTOIAKQKGTGKRAM&row3=HYZDELUCREHUZME&row4=ABUPENIOTNATKTI&row5=RNDDNARBEDLIHCV&row6=LWIMDBIYPLHSXTA&row7=EJHUZFNOCNASEBT&row8=SRDYOJUTBXLGOUC&row9=MDWLCISTOTDUGUO&row10=AOCILQHNOYRKUEQ&row11=RNBLNGXTGGIMKTW&row12=TIYZLYWSOECCEPJ&row13=EDURTREGWYMATDV&row14=LPKOUPNBAAOHMVL&row15=JSCICERONWSMFTS&numwords=15&word1=ALDRIC&word2=ANTOINE&word3=BESANCON&word4=BOURGOGNE&word5=CHARLESMARTEL&word6=CHILDEBRAND&word7=CICERON&word8=ERWIN&word9=GERTRUDE&word10=HERCULE&word11=OCTAVIE&word12=POUILLY&word13=QUIRINUS&word14=SAXON&word15=THIOUIN&";
	identpuzzle = "01livres";
	parser();
}