function puzzle01 ()
 {
	puzzledata = "title=Mots cachés&&row1=XADELAIDENZNMBW&row2=JDFALYKTSUUJUOP&row3=DXRSIAABORIGENE&row4=EIOTJMISVCXCUAO&row5=ATEEELENAHORCPY&row6=KRARYMAHEIPJLAB&row7=IOOSRNKUNFJRIRZ&row8=NBKALGOORLIEDTI&row9=BRCXBEEBUEGSEEM&row10=SALQBLPMOYUHHYP&row11=XLQPOLFDBGTTREA&row12=CLBPOBHTLRREGGR&row13=HUABNAGCEYASCVO&row14=ZNJSPDUPMWDNXXU&row15=AOCAUSTRALIEUZU&numwords=19&word1=ADELAIDE&word2=ABORIGENE&word3=AUSTRALIE&word4=BONAPARTE&word5=BONY&word6=CHIFLEY&word7=DEAKIN&word8=EASTER&word9=ELAINE&word10=EUCLIDE&word11=FISHER&word12=GANBA&word13=KALGOORLIE&word14=MELBOURNE&word15=MYRA&word16=NAPOLEON&word17=NULLARBOR&word18=PERTH&word19=REID&";
	identpuzzle = "01livres";
	parser();
}