function puzzle01 ()
 {

//	puzzledata = "title=Mots cachés&row1=WRTJVIIMPBYFMJS&row2=CTOIAKQKGTGKRAM&row3=HYZDELUCREHUZME&row4=ABUPENIOTNATKTI&row5=RNDDNARBEDLIHCV&row6=LWIMDBIYPLHSXTA&row7=EJHUZFNOCNASEBT&row8=SRDYOJUTBXLGOUC&row9=MDWLCISTOTDUGUO&row10=AOCILQHNOYRKUEQ&row11=RNBLNGXTGGIMKTW&row12=TIYZLYWSOECCEPJ&row13=EDURTREGWYMATDV&row14=LPKOUPNBAAOHMVL&row15=JSCICERONWSMFTS&numwords=1&word1=ALDRIC&";
	puzzledata = "title=Mots cachés&&row1=KXXYMORVOJZBQRH&row2=LGRWMWEICRRFSRJ&row3=CMVQILTKJFMTPAY&row4=MABERNATHYRTMSH&row5=ADQKDDCVCIJPALE&row6=WDHMNIGHTINGALE&row7=BOCMNSALETYBLJL&row8=FCFESRRRASNORCB&row9=WKHALAMUBDTHTIB&row10=VRCONELBTCSEHNE&row11=BSTIQLNKSVCTRLR&row12=TTLEBICQHEGCODP&row13=EUEFNBAHKKRCCNU&row14=EXALDBHLUHKVDYE&row15=FVCICERONDBCJFO&numwords=9&word1=ABERNATHY&word2=CATER&word3=CHARLOTTE&word4=DISRAELI&word5=GLADSTONE&word6=MADDOCK&word7=NIGHTINGALE&word8=PREBBLE&word9=WINCHESTER&";
//	puzzledata = "title=Mots cachés&row1=WRTJVIIMPBYFMJS&row2=CTOIAKQKGTGKRAM&row3=HYZDELUCREHUZME&row4=ABUPENIOTNATKTI&row5=RNDDNARBEDLIHCV&row6=LWIMDBIYPLHSXTA&row7=EJHUZFNOCNASEBT&row8=SRDYOJUTBXLGOUC&row9=MDWLCISTOTDUGUO&row10=AOCILQHNOYRKUEQ&row11=RNBLNGXTGGIMKTW&row12=TIYZLYWSOECCEPJ&row13=EDURTREGWYMATDV&row14=LPKOUPNBAAOHMVL&row15=JSCICERONWSMFTS&numwords=15&word1=ALDRIC&word2=ANTOINE&word3=BESANCON&word4=BOURGOGNE&word5=CHARLESMARTEL&word6=CHILDEBRAND&word7=CICERON&word8=ERWIN&word9=GERTRUDE&word10=HERCULE&word11=OCTAVIE&word12=POUILLY&word13=QUIRINUS&word14=SAXON&word15=THIOUIN&";
	identpuzzle = "01livres";
	parser();
}